version: '2'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-ws
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "80:8080"
    volumes:
      - ./.env:/home/node/app/.env
